# This is a basic workflow that is manually triggered

name: Continuous Integration For Front-end

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
    types: ['published']

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cypress install
        uses: cypress-io/github-action@v2 # <----- This is where mine fails, when cypress is installing
        with:
          runTests: false

      - name: Rebuild node sass
        run: npm rebuild node-sass

      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: n9KfIibpE0oEqk46mutY0Xr2iDTbevS25QVhDZjRDCI
          NETLIFY_SITE_ID: 9e4dd1e6-0782-4bbe-9cc0-395a2b3a719f
          NETLIFY_DEPLOY_MESSAGE: 'Deploy on production'
          NETLIFY_DEPLOY_TO_PROD: true
